// Generated from dalfilo_adv_pipeline_linked - ADV Pipeline.csv.
window.DALFILO_SEED_ASSETS = [
  {
    "id": "asset-51",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Urgency launch — GIF \"Summer Sale è iniziata\"",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · sconti fino al -25%\" animated. SS26 visual identity.",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "First urgency asset. GIF CPM cheapest format (€5.80). Must be live on ADS ON day.",
    "storytelling": "prospecting:\n- La qualità che ami, ora in sconto\n- La Summer Sale Dalfilo è iniziata!\n- Scopri il comfort Dalfilo per notti fresche\n- Scegli i tessuti artigianali per accompagnare le notti d'estate\n- Scopri i tuoi alleati per l'estate\n- Approfitta della Summer Sale e porta a casa la leggerezza dei tessuti Dalfilo ad un prezzo speciale\n\nremarketing:\n- La qualità che ami, ora in sconto\nLa Summer Sale è iniziata, con sconti fino al -25%\n- Porta a casa i tuoi alleati per l'estate con sconti fino al -25%\n- Non lasciarti scappare i prodotti perfetti per notti fresche ad un prezzo speciale\n- Scegli la qualità che dura nel tempo, per notti fresche e comfort continuo\n- Regalati la qualità artigianale con sconti fino al -25%",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-52",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Urgency launch — Static offer banner",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · qualità che ami in sconto\" HP. % offer prominent. SS26 visual identity.",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-53",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Percalle stagionali — Static ambient v1 (botanica collection)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Seasonal product in warm summer ambient light. Offer % prominent.",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26botanica_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Static is conversion backbone. Min 2 variants per collection always.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-54",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Percalle always on — Static ambient v2 (bestseller colour)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "Always on product, natural greens, same offer structure. Second variant for algorithm.",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26botanica_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Second variant gives Andromeda options and reduces creative fatigue.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-55",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle Aria/Cielo/Righe Cielo — Hero \"Freschezza\" Static",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Percale",
    "productCluster": "Novità + Bestseller",
    "hook": "\"Light\" colours to express freshness & percale as traspirant fabric perfect for summer\n\nN.B. exclude aria from DACH asset",
    "landing": "hp",
    "naming": "pr_it_bed_video_brand_ss26percalle_freschezza_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Unique angle: no competitor uses this explicitly. Problem/solution: summer heat → percalle cool.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-56",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Percalle stagionali — GIF colori loop (Botanica+Cielo+Aria)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Animated colour reveal: Malva → Cielo → Aria. 2–3s loop.\n\nN.B. exclude aria from DACH asset",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26percalle_colori_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF CPM €5.80 — lowest in account. Mandatory rt_ asset per active collection.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-57",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Percalle Cielo — Video ambient v1",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "Azzurro cielo in summer light, open window context. Promo visible.",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26cielo_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Cielo was €21.4K in SS25 (3rd colour). BIS video VR 78.9% confirms warm audience.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-58",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Percalle Cielo + Aria + Righe Cielo — GIF colori loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Cielo fabric loop. \"Light\" colours to express freshness & percale as traspirant fabric perfect for summer\n\nN.B. exclude aria from DACH asset",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26cielo_product_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF rt_ CPR €11 vs rm_ CPR €101 — always retargeting stage, never broad rm_.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-59",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Percalle stagionali - carousel (botanica + aria + cielo + righe cielo)",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Seasonal products displayed in carousel to show every ss26 colours + promo communication\n\nN.B. exclude aria from DACH asset",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26cielo_product_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF rt_ CPR €11 vs rm_ CPR €101 — always retargeting stage, never broad rm_.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-60",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Bagno Nido d'ape — Salvia/Crema",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità",
    "hook": "Waffle texture in summer context.",
    "landing": "hp",
    "naming": "pr_it_bath_static_brand_ss26niodape_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Bagno N.d'ape peak is W32–W33 (Ferragosto). Build audience in Fase 1, convert at peak.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-61",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Bagno Nido d'ape — GIF texture loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità",
    "hook": "Waffle weave close-up loop. Slow motion. 2–3s. Salvia/Crema + promo communication",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26niodape_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per collection in rt_. No GIF on this category yet.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-62",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Bagno Nido d'ape — Carousel seasonal & always on",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità",
    "hook": "Wafflepiqué focus on both seasonal & alwyas on + promo communication",
    "landing": "pdp",
    "naming": "rt_it_bath_carousel_brand_ss26niodape_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per collection in rt_. No GIF on this category yet.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-63",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Beach Towels Brezza — Static v1 (context lifestyle)",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Beach",
    "productCluster": "Novità",
    "hook": "Summer context lifestyle. Natural light. Product + colour names.",
    "landing": "hp",
    "naming": "rm_it_bath_video_brand_ss26beach_context_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Summer products need context (sea/pool/outdoor). SS25 beach underperformed due to still-life creative.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-64",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Beach Towels Brezza — GIF texture",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Beach",
    "productCluster": "Novità",
    "hook": "Fabric in sea breeze / slow motion. Loop 2–3s.",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per launch. Outdoor products need movement to communicate feel.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-65",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Beach Towels Brezza + Portofino — carousel",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Beach",
    "productCluster": "Novità",
    "hook": "Display both Portofino & Brezza beach towels in carousel with promo & summer vibes communication",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per launch. Outdoor products need movement to communicate feel.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-66",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Copriletto Nido d'ape — Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Bedspreads",
    "productCluster": "Bestseller",
    "hook": "Light bedspread summer hook. Completa il letto",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26copriletto_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Copriletto push only Weeks 1–3 SS. Demand drops >25°C — stop before Ferragosto.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-67",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Percalle Always on",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "Hand on fabric texture, natural light first 2s.",
    "landing": "hp",
    "naming": "pr_it_bed_video_ugc_ss26botanica_texture_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "UGC best asset in account: CPR €2.85 on 177 results, CPM €6.99 vs brand €9–14.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-68",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Percalle Always on - top down",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "Hand on fabric texture, natural light first 2s.",
    "landing": "hp",
    "naming": "pr_it_bed_video_ugc_ss26botanica_texture_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "UGC best asset in account: CPR €2.85 on 177 results, CPM €6.99 vs brand €9–14.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-69",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle Always on -  Free Embroidery",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Free embroidery push",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ugc_ss26aria_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Aria launched 14 May: €1.5K/day in 4 days. First time in promo — new colourway hook.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-70",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle Always on -  Freschezza",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Light fabrics, freshness",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ugc_ss26aria_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Aria launched 14 May: €1.5K/day in 4 days. First time in promo — new colourway hook.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-71",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "22/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_ + rt_",
    "assetName": "Memory Foam — video texture",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Imbottiti",
    "productCluster": "Novità",
    "hook": "Comfort + breathability for summer",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ss26memory_comfort_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "BIS template at launch: pr_+rm_+rt_ simultaneous. Memory Foam is Fase 1 hero.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-72",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "22/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Memory Foam — Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Imbottiti",
    "productCluster": "Novità",
    "hook": "Product hero + \"Nuovo lancio · Summer Sale\" badge. Clean shot.",
    "landing": "pdp",
    "naming": "rm_it_bed_static_brand_ss26memory_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Static is volume driver alongside UGC. BIS template needs both formats.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-73",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "22/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Memory Foam — GIF product loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Imbottiti",
    "productCluster": "Novità",
    "hook": "Product reveal animation. 2–3s loop. \"Nuovo in estate.\"",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26memory_product_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF per collection mandatory. Lowest CPM format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-74",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "22/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Prodotti Igienici & Memory Foam — \"Completa la tua notte\" Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Imbottiti + Igienici",
    "productCluster": "Novità",
    "hook": "Il letto perfetto per l'estate - Cross-sell angle.",
    "landing": "pdp",
    "naming": "rm_it_bed_static_brand_ss26igienici_crosssell_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "11K letto-baskets YTD: 97% miss Coprimaterasso. AOV +50% when in basket (€188 vs €125). First time in promo.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-75",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "22/06",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Igienici — Carousel cross-sell (Coprimaterasso + Copriguanciale + Memory Foam)",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Imbottiti + Igienici",
    "productCluster": "Novità",
    "hook": "\"Completa il letto.\"  + promo communication",
    "landing": "hp",
    "naming": "rm_it_bed_carousel_brand_ss26igienici_set_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Carousel on warm rm_ audience: right format for product pairing discovery.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-76",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "03/07",
    "deadline": "26/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Free Shipping (+SS promo) // timer urgency",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · sconti fino al -25% + free shipping\". Urgency with timer",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "First urgency asset. GIF CPM cheapest format (€5.80). Must be live on ADS ON day.",
    "storytelling": "communication:\n- la qualità che ami è in sconto, ora senza costi aggiuntivi\n- la spedizione è gratuita ancora per pochi giorni / ancora per poche ore\n- sconti fino al -25% e spedizione gratuita",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-77",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "03/07",
    "deadline": "26/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Free Shipping (+SS promo)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · qualità che ami in sconto\"\n\"Alleati per notti fresche, ora a casa tua senza costi extra\"",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-78",
    "campaign": "Summer Sale 2026 - 2nd Batch",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle always on — Static ambient v2 (bestseller colour)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "Seasonal product in warm summer ambient light. Offer % prominent.",
    "landing": "hp",
    "naming": "pr_it_bed_static_brand_ss26summersale_bestseller_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "prospecting:\n- La qualità che ami, ora in sconto\n- La Summer Sale Dalfilo è iniziata!\n- Scopri il comfort Dalfilo per notti fresche\n- Scegli i tessuti artigianali per accompagnare le notti d'estate\n- Scopri i tuoi alleati per l'estate\n- Approfitta della Summer Sale e porta a casa la leggerezza dei tessuti Dalfilo ad un prezzo speciale\n\nremarketing:\n- La qualità che ami, ora in sconto\nLa Summer Sale è iniziata, con sconti fino al -25%\n- Porta a casa i tuoi alleati per l'estate con sconti fino al -25%\n- Non lasciarti scappare i prodotti perfetti per notti fresche ad un prezzo speciale\n- Scegli la qualità che dura nel tempo, per notti fresche e comfort continuo",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-79",
    "campaign": "Summer Sale 2026 - 2nd Batch",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle Aria/Cielo/Righe Cielo — Hero \"Freschezza\" Static",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "Always on product, natural greens, same offer structure. Second variant for algorithm.",
    "landing": "hp",
    "naming": "pr_it_bed_gif_brand_ss26summersale_freschezza_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-80",
    "campaign": "Summer Sale 2026 - 2nd Batch",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Percalle stagionali — Static ambient v1 (botanica collection)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Bestseller",
    "hook": "\"Light\" colours to express freshness & percale as traspirant fabric perfect for summer",
    "landing": "hp",
    "naming": "pr_it_bed_static_brand_ss26summersale_botanica_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-81",
    "campaign": "Summer Sale 2026 - 2nd Batch",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Bagno Nido d'ape — Salvia/Crema",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità",
    "hook": "Waffle texture in summer context.",
    "landing": "hp",
    "naming": "pr_it_bath_static_brand_ss26nidodape_lifestyle_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-82",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Free Embroidery (+SS promo) // timer urgency",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · sconti fino al -25% + free embroidery\". Urgency with timer",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "First urgency asset. GIF CPM cheapest format (€5.80). Must be live on ADS ON day.",
    "storytelling": "communication:\n- aggiungi un dettaglio speciale senza costi aggiuntivi\n- solo per poco, il ricamo è in omaggio\n- la summer sale è attiva con sconti fino al -25% e, solo per poco, il ricamo è gratuito!",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-83",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "10/07",
    "deadline": "07/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Free Embroidery (+SS promo)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · qualità che ami in sconto\"\n\"Personalizza il tuo prodotto preferito, gratis\"",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-84",
    "campaign": "Summer Sale 2026 - 3rd Batch",
    "goLive": "17/07",
    "deadline": "14/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Percalle mixed colours - gif freschezza focus",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità + Bestseller",
    "hook": "\"Summer Sale · qualità che ami in sconto\"\n\"Alleati per notti fresche, ora a casa tua senza costi extra\"\n\nincludere mix colori, da botanica, cielo, always on",
    "landing": "hp",
    "naming": "rt_it_bed_gif_brand_ss26summersale_percale_mixed_v2_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "prospecting:\n- La qualità che ami, ora in sconto\n- La Summer Sale Dalfilo è iniziata!\n- Scopri il comfort Dalfilo per notti fresche\n- Scegli i tessuti artigianali per accompagnare le notti d'estate\n- Scopri i tuoi alleati per l'estate\n- Approfitta della Summer Sale e porta a casa la leggerezza dei tessuti Dalfilo ad un prezzo speciale\n\nremarketing:\n- La qualità che ami, ora in sconto\nLa Summer Sale è iniziata, con sconti fino al -25%\n- Porta a casa i tuoi alleati per l'estate con sconti fino al -25%\n- Non lasciarti scappare i prodotti perfetti per notti fresche ad un prezzo speciale\n- Scegli la qualità che dura nel tempo, per notti fresche e comfort continuo\n- Regalati la qualità artigianale con sconti fino al -25%",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-85",
    "campaign": "Summer Sale 2026 - 3rd Batch",
    "goLive": "17/07",
    "deadline": "14/07",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Igienici — gif \"completa il tuo letto\" \n(Coprimaterasso + Copriguanciale + Memory Foam)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Imbottiti + Igienici",
    "productCluster": "Novità",
    "hook": "\"Completa il letto.\"  + promo communication",
    "landing": "hp",
    "naming": "rm_it_bed_gif_brand_ss26igienici_set_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-86",
    "campaign": "Summer Sale 2026 - 3rd Batch",
    "goLive": "17/07",
    "deadline": "14/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Accappatoio Nido d'ape — Salvia/Crema",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità",
    "hook": "Waffle texture in summer context.",
    "landing": "hp",
    "naming": "pr_it_bath_gif_brand_ss26nidodape_lifestyle_v3_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-87",
    "campaign": "Summer Sale 2026 - 3rd Batch",
    "goLive": "17/07",
    "deadline": "14/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Beach Towels Brezza & Portofino — GIF texture",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Beach",
    "productCluster": "Novità + Bestseller",
    "hook": "Fabric in sea breeze / slow motion. Loop 2–3s.",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26beach_texture_v2_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-88",
    "campaign": "Summer Sale 2026 - 3rd Batch",
    "goLive": "17/07",
    "deadline": "14/07",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Copriletto Nido d'ape — Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Bedspreads",
    "productCluster": "Bestseller",
    "hook": "Light bedspread summer hook. Completa il letto",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26copriletto_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-89",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Urgency launch — Ultimi pezzi, ultime taglie (last chance)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · sconti fino al -35%\". \nMix prodotti percalle last chance (both sets & single products)",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "prospecting:\n- Assicurati il comfort Dalfilo per notti fresche prima che le scorte esauriscano\n- Approfitta della Summer Sale: porta a casa la leggerezza dei tessuti Dalfilo con sconti fino al -35%\n- Scegli la qualità che ami, ora fino a -35%\n- Ultimi pezzi disponibili: scegli i tessuti artigianali per accompagnare le notti d'estate\n\nremarketing:\n- La qualità che ami, da oggi con sconti fino al -35%\n-Le quantità sono limitate: porta a casa i tuoi alleati per l'estate fino a -35%\n- I prodotti perfetti per le tue notti fresche sono ora in sconto fino al -35%: non farteli sfuggire\n- È il momento di regalarsi la qualità artigianale con sconti fino al -35%",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-90",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Urgency launch — Static offer banner",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · sconti fino al -35%\". \nAnimated graphic identity (such as in DD26 reshuffle)",
    "landing": "hp",
    "naming": "rm_it_mixed_video_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-91",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "SS26 Urgency launch — Ultimi pezzi, ultime taglie (last chance)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · sconti fino al -35%\". \nUse hero picture bedsheet set w/ last chance graphic identity",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-92",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Last chance - static lifestyle & freshness",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la freschezza in sconto",
    "landing": "pdp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-93",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Last chance - static lifestyle & freshness",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la freschezza in sconto",
    "landing": "pdp",
    "naming": "rm_it_mixed_video_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-94",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Last chance carousel - bedsheet sets",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultime taglie // ultima occasione per acquistare, con sconto fino al -35%",
    "landing": "pdp",
    "naming": "rm_it_mixed_carousel_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-95",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Last chance carousel - single items only",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultime taglie // ultima occasione per acquistare, con sconto fino al -35%",
    "landing": "pdp",
    "naming": "rm_it_mixed_carousel_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-96",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Copriletto Nido d'ape — Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Bedspreads",
    "productCluster": "Bestseller",
    "hook": "Light bedspread summer hook. Completa il letto",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26copriletto_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-97",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Copriletto Nido d'ape — Static",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Bedspreads",
    "productCluster": "Bestseller",
    "hook": "Light bedspread summer hook. Completa il letto",
    "landing": "hp",
    "naming": "rm_it_bed_video_brand_ss26copriletto_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-98",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Copriletto Nido d'ape — Static",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Bedspreads",
    "productCluster": "Bestseller",
    "hook": "Light bedspread summer hook. Completa il letto",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26copriletto_offer_v3_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-99",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Memory Foam — Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Imbottiti",
    "productCluster": "Novità",
    "hook": "Product hero + Completa il letto // letto perfetto per l'estate",
    "landing": "pdp",
    "naming": "rm_it_bed_static_brand_ss26memory_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Static is volume driver alongside UGC. BIS template needs both formats.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-100",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Last chance - static lifestyle",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Classic Line",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto",
    "landing": "pdp",
    "naming": "pr_it_bath_static_brand_ss26lastchance_classic_line_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-101",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Last chance - static lifestyle focus texture",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Classic Line",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto",
    "landing": "pdp",
    "naming": "pr_it_bath_static_brand_ss26lastchance_classic_line_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-102",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Last chance carousel - single items only",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Classic Line",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto",
    "landing": "pdp",
    "naming": "pr_it_bath_video_brand_ss26lastchance_classic_line_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-103",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Bagno Nido d'ape — Salvia/Crema",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità + Bestseller",
    "hook": "Waffle texture in summer context. \nfollow last chance communication & visual identity",
    "landing": "hp",
    "naming": "pr_it_bath_static_brand_ss26niodape_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Bagno N.d'ape peak is W32–W33 (Ferragosto). Build audience in Fase 1, convert at peak.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-104",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Bagno Nido d'ape — GIF texture loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità + Bestseller",
    "hook": "Waffle weave close-up loop. Slow motion. 2–3s. Salvia/Crema \nfollow last chance communication & visual identity",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26niodape_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per collection in rt_. No GIF on this category yet.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-105",
    "campaign": "Summer Sale 2026 - 1st Batch",
    "goLive": "03/07",
    "deadline": "17/06",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rt_",
    "assetName": "Bagno Nido d'ape — Carousel seasonal & always on",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Nido",
    "productCluster": "Novità + Bestseller",
    "hook": "Wafflepiqué focus on both seasonal & alwyas on \nfollow last chance communication & visual identity",
    "landing": "pdp",
    "naming": "rt_it_bath_carousel_brand_ss26niodape_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF mandatory per collection in rt_. No GIF on this category yet.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-106",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Beach Towels Brezza + Portofino — carousel",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Beach",
    "productCluster": "Ultimi Pezzi",
    "hook": "Display both Portofino & Brezza beach towels in carousel with promo & summer vibes communication // last chance",
    "landing": "pdp",
    "naming": "rt_it_bath_carousel_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-107",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Beach Towels Brezza + Portofino — carousel",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Beach",
    "productCluster": "Ultimi Pezzi",
    "hook": "Display both Portofino & Brezza beach towels in carousel with promo & summer vibes communication // last chance",
    "landing": "pdp",
    "naming": "rt_it_bath_video_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-108",
    "campaign": "Summer Sale 2026 - Last Chance - 1st Batch",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "Beach Towels Liberty - static ultimissimi pezzi (check availability!)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Beach",
    "productCluster": "Ultimi Pezzi",
    "hook": "Last chance for Liberty beach towels",
    "landing": "pdp",
    "naming": "rt_it_bath_carousel_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-109",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Free Shipping (+SS promo) // timer urgency",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · sconti fino al -25% + free shipping\". Urgency with timer",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "First urgency asset. GIF CPM cheapest format (€5.80). Must be live on ADS ON day.",
    "storytelling": "communication:\n- ultimi pezzi, ultime taglie dei prodotti più amati, ora scontati fino al -35%\n- la spedizione è gratuita ancora per pochi giorni / poche ore\n- ultima occasione per portare a casa con sconti fino al -35% e senza costi aggiuntivi\n- sconti fino al -35% e spedizione gratuita",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-110",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "30/07",
    "deadline": "23/07",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Free Shipping (+SS promo)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · qualità che ami in sconto\"\n\"Alleati per notti fresche, ora a casa tua senza costi extra\"",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-111",
    "campaign": "Summer Sale 2026 - Last Chance - 2nd Batch",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Satin bedsheet set - gif",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Satin",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto // aggiungere nella gif sia item ultimi pezzi che best seller, con claim \"fino al -35%",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "prospecting:\n- Assicurati il comfort Dalfilo per notti fresche prima che le scorte esauriscano\n- Approfitta della Summer Sale: porta a casa la leggerezza dei tessuti Dalfilo con sconti fino al -35%\n- Scegli la qualità che ami, ora fino a -35%\n- Ultimi pezzi disponibili: scegli i tessuti artigianali per accompagnare le notti d'estate\n\nremarketing:\n- La qualità che ami, da oggi con sconti fino al -35%\n-Le quantità sono limitate: porta a casa i tuoi alleati per l'estate fino a -35%\n- I prodotti perfetti per le tue notti fresche sono ora in sconto fino al -35%: non farteli sfuggire\n- È il momento di regalarsi la qualità artigianale con sconti fino al -35%",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-112",
    "campaign": "Summer Sale 2026 - Last Chance - 2nd Batch",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Linen bedsheet set - gif",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Linen",
    "productCluster": "Ultimi Pezzi",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto // aggiungere nella gif sia item ultimi pezzi che best seller, con claim \"fino al -35%",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-113",
    "campaign": "Summer Sale 2026 - Last Chance - 2nd Batch",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_",
    "assetName": "Kids line BED - static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Letto Percalle",
    "productCluster": "Novità",
    "hook": "Use last chance visual identity to be coherent, but the claim needs to be more gneeral on \"La qualità Dalfilo per i tuoi bimbi, anche in estate\" // no discounts",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-114",
    "campaign": "Summer Sale 2026 - Last Chance - 2nd Batch",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Kids line BATH - static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Classica",
    "productCluster": "Novità",
    "hook": "Use last chance visual identity to be coherent, but the claim needs to be more gneeral on \"La qualità Dalfilo per i tuoi bimbi, anche in estate\" // no discounts",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-115",
    "campaign": "Summer Sale 2026 - Last Chance - 2nd Batch",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "Bath Classic line - carousel",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno Classica",
    "productCluster": "Novità + Bestseller",
    "hook": "Ultimi pezzi, ultima occasione per portare a casa la qualità in sconto // aggiungere nella gif sia item ultimi pezzi che best seller, con claim \"fino al -35%",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-116",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_ + rt_",
    "assetName": "SS26 Free Embroidery (+LC promo) // timer urgency",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · sconti fino al -35% + free embroidery\". Urgency with timer",
    "landing": "hp",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "First urgency asset. GIF CPM cheapest format (€5.80). Must be live on ADS ON day.",
    "storytelling": "communication:\n- aggiungi un dettaglio speciale senza costi aggiuntivi\n- solo per poco, il ricamo è in omaggio\n- la summer sale è attiva con sconti fino al -35% e, solo per poco, il ricamo è gratuito!",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-117",
    "campaign": "Summer Sale 2026 - WKND Promo",
    "goLive": "13/08",
    "deadline": "07/08",
    "country": "all markets",
    "priority": "High",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "SS26 Free Embroidery (+LC promo)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Novità",
    "hook": "\"Summer Sale · ultimi pezzi, ultime taglie\"\n\"Personalizza il tuo prodotto preferito, gratis\"",
    "landing": "hp",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-118",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Static percale - focus FOMO & PROMO",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · ultimi pezzi, ultime taglie\"\n\nuse only percale last chance",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "prospecting:\n- Ultima chiamata: la qualità che ami, ora per pochissime ore fino a -35%\n- La Summer Sale Dalfilo sta per finire: sconti fino a -35% ancora per pochissimo!\n- Ultimi pezzi disponibili per assicurarti il comfort Dalfilo per notti fresche\n- Scegli ora i tessuti artigianali per le tue notti d'estate\nLa Summer Sale sta per scadere: porta a casa la leggerezza dei tessuti Dalfilo a prezzo speciale prima  sia troppo tardi\n\nremarketing:\n- Resta poco tempo: la qualità che ami è in sconto fino al -35% ancora per poco\n- Mancano poche ore: porta a casa i tuoi preferiti con sconti fino al -35%\n- I pezzi sono limitati: non lasciarti scappare i tuoi preferiti\n- Ultimi giorni: assicurati la qualità che dura nel tempo prima che le scorte riniwdqno\n- Ora o mai più: regalati la qualità artigianale con sconti fino al -35%",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-119",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "VIdeo percale - focus FOMO & PROMO",
    "format": "Video",
    "creativeType": "AI",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · ultimi pezzi, ultime taglie\"\n\nuse only percale last chance",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-120",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Gif product mix - focus FOMO & PROMO",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Prodotti",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · ultimi pezzi, ultime taglie\"\n\nuse both percale, bath classic line, beach products",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-121",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "pr_ + rm_",
    "assetName": "Gif product mix - focus FOMO & PROMO",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Prodotti",
    "productCluster": "Ultimi Pezzi",
    "hook": "\"Summer Sale · ultimi pezzi, ultime taglie\"\n\nuse both percale, bath classic line, beach products",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-122",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "URGENCY  last days SS - static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\" Summer Sale - sconti fino al -35% ancora per poco \"",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-123",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "URGENCY  last days SS - gif (timer)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\" Summer Sale - sconti fino al -35% ancora per poco \"",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-124",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "URGENCY  last hours SS - static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\" Summer Sale - sconti fino al -35% ancora per poco \"",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-125",
    "campaign": "Summer Sale 2026 - Last Chance - 3rd Batch",
    "goLive": "24/08",
    "deadline": "19/08",
    "country": "all markets",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "funnel": "rm_",
    "assetName": "URGENCY  last hours SS - gif (timer)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "Ultimi Pezzi",
    "hook": "\" Summer Sale - sconti fino al -35% ancora per poco \"",
    "landing": "hp",
    "naming": "",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  }
];
